deploy-cert-manager: refactoring
refactoring to make it easy to evolve

diff --git a/script/deploy-cert-manager b/script/deploy-cert-manager
--- a/script/deploy-cert-manager
+++ b/script/deploy-cert-manager
@@ -1,19 +1,21 @@
 #!/usr/bin/env bash
 # author: joe.zheng
-# version: 23.12.03
+# version: 24.03.30
 
 set -e
 
 SELF="$(basename $0)"
 SELF_VERSION="$(sed -n '1,4s/# version: \(.*\)/\1/p' $0)"
 NAME="${SELF#*-}"
+NAME_CTL="cmctl"
 
 SUDO="sudo"
 if [[ $(id -u) == "0" ]]; then
   SUDO=""
 fi
 
-VERSION="1.12.6"      # version to deploy
+VERSION="1.12.6"      # version to deploy, check https://cert-manager.io/docs/releases/
+CUR_VER=              # current version if any
 DRY_RUN=n             # print information only
 MIRROR="auto"         # mirror option
 MIRRORS="yes no auto" # valid mirror options
@@ -23,16 +25,19 @@ OFFLINE=${OFFLINE:-n} # no external network
 
 REPO_URL="https://github.com/cert-manager/cert-manager"
 MIRROR_URL="${MIRROR_URL:-https://iffi.me/proxy}"
-GCLOUD_URL="https://packages.cloud.google.com"
+GITHUB_RAW="https://raw.githubusercontent.com"    # github raw content base url
 
 VARIANT="$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/x86_64/amd64/')"
+INSTALL_DIR_BIN="/usr/local/bin"
+
 TIMEOUT="300s"
 NAMESPACE="$NAME"
 
 CACHE="cache"
-CACHE_MANIFESTS="$CACHE/manifests"
-CACHE_PACKAGES="$CACHE/packages/common"
 CACHE_RUN="$CACHE/run/$SELF"
+CACHE_PACKAGES="$CACHE/packages/common"
+CACHE_MANIFESTS="$CACHE/manifests"
+CACHE_DOWNLOADING="$CACHE/.download"
 
 function msg() {
   echo "> $@"
@@ -60,6 +65,7 @@ Cache:
   To speed up deployment, the required files will be cached at "$CACHE"
 
 Environment variables:
+
   MIRROR_URL:  mirror to use, default: $MIRROR_URL
   OFFLINE:     force into offline mode [y n], default: $OFFLINE
 
@@ -84,8 +90,8 @@ EOF
 
 function current_version() {
   local version=
-  if which cmctl >/dev/null; then
-    version="$(cmctl version --short 2>/dev/null | sed -n 's/Server Version: v\(.*\)/\1/p')"
+  if which $NAME_CTL >/dev/null; then
+    version="$($NAME_CTL version --short 2>/dev/null | sed -n 's/Server Version: v\(.*\)/\1/p')"
   fi
   echo $version
 }
@@ -99,8 +105,8 @@ function validate_sudo() {
 
 function main() {
   # adjust default version if already deployed
-  local deployed="$(current_version)"
-  VERSION="${deployed:-$VERSION}"
+  local CUR_VER="$(current_version)"
+  VERSION="${CUR_VER:-$VERSION}"
 
   while getopts ":m:v:hnRU" opt
   do
@@ -121,12 +127,10 @@ function main() {
   done
   shift $((OPTIND-1))
 
-  for v in CACHE DRY_RUN MIRROR MIRROR_URL OFFLINE RESET UNINSTALL VERSION
+  for v in CACHE DRY_RUN MIRROR MIRROR_URL OFFLINE RESET UNINSTALL VERSION CUR_VER
   do
     eval echo "$v: \${$v}"
   done
-
-  msg "deployed version: $deployed"
 
   [[ $DRY_RUN == "y" ]] && exit
 
@@ -139,48 +143,36 @@ function main() {
   local manifest_dir="$CACHE_MANIFESTS/$NAME-$VERSION"
   local manifest_list="cert-manager.yaml"
   local package_dir="$CACHE_PACKAGES/$NAME-$VERSION"
-  local package_list="cmctl"
-  local install_dir="/usr/local/bin"
+  local package_list="$NAME_CTL"
 
   mkdir -p $package_dir $manifest_dir
 
-  local base_url="$REPO_URL"
-  if [[ $NEED_MIRROR == "y" ]]; then
-    base_url="$MIRROR_URL/$REPO_URL"
+  if [[ $OFFLINE == "y" ]]; then
+    msg "WARNING: offline mode, cache must be ready"
+  else
+    msg "download manifests"
+    for n in $manifest_list; do
+      local u="$REPO_URL/releases/download/v$VERSION/$n"
+      download_file "$(mirror_url $u)" "$manifest_dir/$n"
+    done
+
+    msg "download packages"
+    for n in $package_list; do
+      local f="$n-$VARIANT.tar.gz"
+      local u="$REPO_URL/releases/download/v$VERSION/$f"
+      download_file "$(mirror_url $u)" "$package_dir/$f"
+  done
   fi
 
-  msg "download manifests"
-  for n in $manifest_list; do
-    local f="$manifest_dir/$n"
-    if [[ ! -e "$f" ]]; then
-      if [[ $OFFLINE == "y" ]]; then
-        err "no cache found: $f"
-        exit 1
-      fi
-      local u="$base_url/releases/download/v$VERSION/$n"
-      msg "download $u -> $f"
-      curl -L $u > $f
-    fi
-  done
-
-  msg "download packages"
+  msg "extract packages to $CACHE_RUN"
   for n in $package_list; do
-    local f="$package_dir/$n"
-    msg "check $f"
-    if [[ ! -e "$f" ]]; then
-      if [[ $OFFLINE == "y" ]]; then
-        err "no cache found: $f"
-        exit 1
-      fi
-      local u="$base_url/releases/download/v$VERSION/$n-$VARIANT.tar.gz"
-      msg "download $u -> $f"
-      curl -L $u | tar xz -C $package_dir $n
-    fi
+    local f="$n-$VARIANT.tar.gz"
+    tar xzf "$package_dir/$f" -C $CACHE_RUN $n
   done
 
   if [[ $RESET == "y" ]]; then
     local kd="kubectl delete --ignore-not-found"
-    if [[ -n "$deployed" ]]; then
+    if [[ -n "$CUR_VER" ]]; then
       msg "clean it up first"
       $kd -A --all issuer,clusterissuer,certificate,certificaterequest,order,challenge
     fi
@@ -198,18 +190,18 @@ function main() {
   if [[ $UNINSTALL == "y" ]]; then
     msg "uninstall $package_list"
     for n in "$package_list"; do
-      $SUDO rm -f $install_dir/$n
+      $SUDO rm -f $INSTALL_DIR_BIN/$n
     done
   else
     msg "install $package_list"
     for n in "$package_list"; do
-      $SUDO install -t $install_dir $package_dir/$n
+      $SUDO install -t $INSTALL_DIR_BIN $CACHE_RUN/$n
     done
   fi
 
   if [[ $RESET != "y" ]]; then
     msg "wait until ready (timeout: $TIMEOUT)"
-    cmctl check api --wait=$TIMEOUT
+    $NAME_CTL check api --wait=$TIMEOUT
 
 cat <<EOF > $CACHE_RUN/test-selfsigned.yaml
 apiVersion: v1
@@ -253,7 +245,7 @@ kubectl apply -f $CACHE_RUN/test-selfsigned.yaml
 # list all the issuers and certificates
 kubectl get issuer,certificate -A
 
-# check more details from $REPO_URL
+# check more details in $REPO_URL
 EOF
   fi
 
@@ -276,10 +268,15 @@ function check_prerequisites() {
   fi
 }
 
+# the target URL is reachable but the response may be 4xx or 5xx
+function can_access() {
+   curl -IL -s -m 5 $1 >/dev/null 2>&1
+}
+
 function check_network() {
   msg "check network"
   if [[ $OFFLINE != 'y' ]]; then
-    if ! curl -s -m 3 -I example.com >/dev/null; then
+    if ! can_access example.com; then
       msg "can't access external network"
       OFFLINE="y"
     fi
@@ -287,17 +284,17 @@ function check_network() {
   msg "offline mode: $OFFLINE"
 }
 
-NEED_MIRROR=n
+USE_MIRROR=n
 function check_mirror() {
-  msg "is mirror needed"
+  msg "use mirror or not"
   if [[ $MIRROR == "auto" ]]; then
     MIRROR=yes # default as needed
     if [[ $OFFLINE == "y" ]]; then
       msg "offline mode, assume mirror is needed"
     else
-      msg "check whether we can access google cloud"
-      local target="$GCLOUD_URL"
-      if curl -s -m 5 $target >/dev/null 2>&1; then
+      msg "check whether we can access github"
+      local target="$GITHUB_RAW"
+      if can_access $target; then
         msg "curl $target is OK"
         MIRROR=no
       else
@@ -306,20 +303,50 @@ function check_mirror() {
     fi
   fi
   if [[ $MIRROR == "yes" ]]; then
-    NEED_MIRROR=y
+    msg "mirror is needed"
+    if can_access $MIRROR_URL; then
+      USE_MIRROR="y"
+    else
+      err "failed to access mirror ($MIRROR_URL)"
+    fi
   fi
-  msg "need mirror: $NEED_MIRROR"
+  msg "use mirror: $USE_MIRROR"
+}
+
+function mirror_url() {
+  local origin="${1:?argument missing}"
+
+  if [[ $USE_MIRROR = "y" ]]; then
+    echo -n "$MIRROR_URL/$origin"
+  else
+    echo -n "$origin"
+  fi
 }
 
 function ensure_workdir() {
   msg "ensure workdir"
 
-  for d in $CACHE_MANIFESTS $CACHE_PACKAGES $CACHE_RUN; do
+  for d in $CACHE_MANIFESTS $CACHE_PACKAGES $CACHE_RUN $CACHE_DOWNLOADING; do
     if [[ ! -d $d ]]; then
       msg "create dir: $d"
       mkdir -p $d
     fi
   done
+}
+
+function download_file() {
+  local src="${1:?missing source url}"
+  local dst="${2:?missing destination}"
+
+  if [[ -f "$dst" ]]; then
+    msg "already exist: $dst"
+  else
+    msg "download: $src"
+    local tmp="$CACHE_DOWNLOADING/$(basename $dst)"
+    $RUN curl -fsSL $src > $tmp
+    $RUN mkdir -p $(dirname $dst) && mv $tmp $dst
+    msg "saved at: $dst"
+  fi
 }
 
 main "$@"
